apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-05-29T18:59:47Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  generateName: petclinic-app-
  labels:
    app: petclinic-app
  name: petclinic-app-service1
  namespace: default
  resourceVersion: "5252"
  selfLink: /api/v1/namespaces/default/services/petclinic-app-wrqr7
  uid: c5ccc875-feba-40af-b276-dec42b02250e
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31350
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.185.52.30
