apiVersion: v1
kind: Pod
metadata:
  name: test-pd1
spec:
  containers:
    - image: nginx:latest
      name: test-container
      volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4

