name: Java Spring CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    strategy:
      matrix:
        java-version: [8]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Test and Build
        run: ./mvnw jetty:run-war